# Copyright (C) 2018-2021 Adam Leszczynski.
#
# This file is part of Open Log Replicator docker template.
# 
# Open Log Replicator is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation; either version 3, or (at your option)
# any later version.
# 
# Open Log Replicator is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Open Log Replicator; see the file LICENSE.txt  If not see
# <http://www.gnu.org/licenses/>.
#
# OpenLogReplicator Dockerfile
# --------------------------
# This is the Dockerfile for OpenLogReplicator
#
# REQUIRED FILES TO BUILD THIS IMAGE
# ----------------------------------
#
# (1) instantclient-basic-linux.x64-19.11.0.0.zip
# (2) instantclient-sdk-linux.x64-19.11.0.0.zip
#     Download from https://www.oracle.com/database/technologies/instant-client.html
#
# HOW TO BUILD THIS IMAGE
# -----------------------
# Put all downloaded files in the same directory as this Dockerfile
# Run:
#       $ docker build -t bersler/openlogreplicator:centos-8 -f Dockerfile-centos-8 .
#

FROM centos:8 as builder

MAINTAINER Adam Leszczynski <aleszczynski@bersler.com>

COPY instantclient-basic-linux.x64-19.11.0.0.0dbru.zip /tmp/instantclient-basic-linux.x64-19.11.0.0.0dbru.zip
COPY instantclient-sdk-linux.x64-19.11.0.0.0dbru.zip /tmp/instantclient-sdk-linux.x64-19.11.0.0.0dbru.zip

ENV LANG en_US.UTF-8
ENV LD_LIBRARY_PATH=/opt/instantclient_19_11:/opt/librdkafka/lib

RUN set -eux ; \
    yum install -y diffutils make gcc gcc-c++ git file unzip libasan libaio-devel libnsl autoconf automake libtool wget tar ; \
    cd /opt ; \
    unzip /tmp/instantclient-basic-linux.x64-19.11.0.0.0dbru.zip ; \
    rm /tmp/instantclient-basic-linux.x64-19.11.0.0.0dbru.zip ; \
    unzip /tmp/instantclient-sdk-linux.x64-19.11.0.0.0dbru.zip ; \
    rm /tmp/instantclient-sdk-linux.x64-19.11.0.0.0dbru.zip ; \
    cd /opt/instantclient_19_11 ; \
    ln -s libclntshcore.so.19.1 libclntshcore.so ; \
    mkdir /opt/librdkafka-src ; \
    cd /opt/librdkafka-src ; \
    git clone https://github.com/edenhill/librdkafka ; \
    cd librdkafka ; \
    ./configure --prefix=/opt/librdkafka ; \
    make ; \
    make install ; \
    cd /opt ; \
    git clone https://github.com/Tencent/rapidjson ; \
    mkdir /opt/OpenLogReplicator ; \
    mkdir /opt/OpenLogReplicator/scripts-src ; \
    mkdir /opt/OpenLogReplicator-src ; \
    cd /opt/OpenLogReplicator-src ; \
    git clone https://github.com/bersler/OpenLogReplicator ; \
    cd /opt/OpenLogReplicator-src/OpenLogReplicator ; \
    autoreconf -f -i ; \
    ./configure CXXFLAGS='-O3' --with-rapidjson=/opt/rapidjson --with-rdkafka=/opt/librdkafka --with-instantclient=/opt/instantclient_19_11 ; \
    make ; \
    mv src/OpenLogReplicator /opt/OpenLogReplicator ; \
    mv scripts/* /opt/OpenLogReplicator/scripts-src ; \
    mv AUTHORS /opt/OpenLogReplicator ; \
    mv CHANGELOG /opt/OpenLogReplicator ; \
    mv LICENSE /opt/OpenLogReplicator ; \
    mv README.md /opt/OpenLogReplicator ; \
    rm -rf /opt/OpenLogReplicator-src /opt/rapidjson /opt/librdkafka-src /opt/protobuf-src ; \
    yum -y remove make gcc gcc-c++ git file unzip autoconf automake libtool wget ; \
    yum -y autoremove ; \
    yum clean all ; \
    rm -rf /var/cache/yum ; \
    groupadd -g 1000 user1 ; \
    useradd -u 1000 user1 -g user1 ; \
    su - user1 /opt/OpenLogReplicator/OpenLogReplicator --version

USER user1:user1
WORKDIR /opt/OpenLogReplicator
ENTRYPOINT ./OpenLogReplicator
